In [ ]:
# PD Model Validation – Data Preparation & Sanity Checks
# - Load raw CSV files
# - Basic structure validation
# - Duplicate and missing value overview
# - Prepare datasets for further analysis

In [19]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 50)

In [20]:
dat_scoring = pd.read_csv("../data_raw/dat_scoring.csv", na_values=["NA"])
dat_arrangement = pd.read_csv("../data_raw/dat_arrangement.csv", na_values=["NA"])
dat_obligor = pd.read_csv("../data_raw/dat_obligor.csv", na_values=["NA"])
par_pools = pd.read_csv("../data_raw/par_pools.csv", na_values=["NA"])
par_model = pd.read_csv("../data_raw/par_model.csv", na_values=["NA"])

In [3]:
dat_scoring.head()

   YEAR   IP_ID     AR_ID            PD  PD_POOL  DFLT_FLAG
0  2022  CFG053   2795120  9.925260e-01      5.0          1
1  2022  NNA451  10210477  2.656939e-05      1.0          0
2  2022  VLZ931  24787848  3.514735e-06      1.0          0
3  2022  VVF064  35869938  5.868028e-06      1.0          0
4  2022  DXH176  71765042  8.378070e-07      1.0          0

In [4]:
dat_arrangement.head()

      AR_ID  YEAR  DEBT_RATIO   DPD  M_LAST_DPD
0  76269627  2023    0.330044   NaN         NaN
1  53720950  2023    0.085891   NaN         NaN
2  46362866  2024    0.720821   8.0         8.0
3  60295607  2023    0.845081   NaN         NaN
4  63029620  2023    0.821967  43.0         0.0

In [5]:
dat_obligor.head()

    IP_ID  YEAR   AGE  EDUCATION
0  CFG053  2022  70.0        2.0
1  NNA451  2022  72.0        2.0
2  VLZ931  2022  44.0        2.0
3  VVF064  2022  63.0        1.0
4  DXH176  2022  20.0        1.0

In [21]:
par_pools

   LABEL   START     END
0      1    -inf  0.0008
1      2  0.0008  0.0030
2      3  0.0030  0.0090
3      4  0.0090  0.0480
4      5  0.0480     inf

In [22]:
par_model

,VARIABLE,LABEL,MEAN,ST.DEV,MIN,MAX,MISSING_VALUE,ESTIMATE
0,INTERCEPT,INTERCEPT,NaN,NaN,NaN,NaN,NaN,7.2568
1,AGE,Age of the obligor,51.0000,15.000000,18.0,75.0,75.0,0.5908
2,EDUCATION_1,Basic education/ Student,NaN,NaN,NaN,NaN,1.0,2.0368
3,EDUCATION_2,Secondary education,NaN,NaN,NaN,NaN,1.0,2.8567
4,EDUCATION_3,Tertiary (university) education,NaN,NaN,NaN,NaN,1.0,0.0000
5,DEBT_RATIO,Remaining debt ratio,0.3436,0.280800,0.0,1.0,1.0,0.4261
6,MAX_DPD,Past due days in last 24 months. Maximum of al...,30.0000,80.000000,0.0,400.0,0.0,0.8245
7,MIN_M_LAST_DPD,Months since last past due. Minimum of all obl...,7.0000,2.645751,0.0,24.0,24.0,-2.2365

In [6]:
dat_scoring.info()

<class 'pandas.DataFrame'>
RangeIndex: 36000 entries, 0 to 35999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YEAR       36000 non-null  int64
 1   IP_ID      36000 non-null  str
 2   AR_ID      36000 non-null  int64
 3   PD         35105 non-null  float64
 4   PD_POOL    35105 non-null  float64
 5   DFLT_FLAG  36000 non-null  int64
dtypes: float64(2), int64(3), str(1)
memory usage: 1.6 MB

In [7]:
dat_arrangement.info()

<class 'pandas.DataFrame'>
RangeIndex: 35820 entries, 0 to 35819
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AR_ID       35820 non-null  int64
 1   YEAR        35820 non-null  int64
 2   DEBT_RATIO  34650 non-null  float64
 3   DPD         4508 non-null   float64
 4   M_LAST_DPD  4508 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 1.4 MB

In [8]:
dat_obligor.info()

<class 'pandas.DataFrame'>
RangeIndex: 31592 entries, 0 to 31591
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IP_ID      31592 non-null  str
 1   YEAR       31592 non-null  int64
 2   AGE        30961 non-null  float64
 3   EDUCATION  30803 non-null  float64
dtypes: float64(2), int64(1), str(1)
memory usage: 987.4 KB

In [9]:
print(dat_scoring.shape)
print(dat_arrangement.shape)
print(dat_obligor.shape)

(36000, 6)
(35820, 5)
(31592, 4)

In [10]:
print(dat_scoring[['YEAR', 'AR_ID']].drop_duplicates().shape)
print(dat_arrangement[['YEAR', 'AR_ID']].drop_duplicates().shape)
print(dat_obligor[['YEAR', 'IP_ID']].drop_duplicates().shape)

(36000, 2)
(34262, 2)
(31592, 2)

In [13]:
dat_arrangement[['YEAR', 'AR_ID']].value_counts().head()

YEAR  AR_ID
2024  16184571    3
2023  15107955    3
2022  73029996    3
      41286769    3
2024  97699488    3
Name: count, dtype: int64

In [14]:
dat_arrangement[(dat_arrangement['YEAR'] == 2024) & (dat_arrangement['AR_ID'] == 16184571)]

          AR_ID  YEAR  DEBT_RATIO  DPD  M_LAST_DPD
367    16184571  2024    0.135067  NaN         NaN
34233  16184571  2024         NaN  NaN         NaN
34964  16184571  2024    0.135067  NaN         NaN

In [15]:
dat_arrangement[(dat_arrangement['YEAR'] == 2023) & (dat_arrangement['AR_ID'] == 15107955)]

          AR_ID  YEAR  DEBT_RATIO  DPD  M_LAST_DPD
2106   15107955  2023    0.039826  NaN         NaN
34558  15107955  2023         NaN  NaN         NaN
35202  15107955  2023    0.039826  NaN         NaN

In [16]:
dat_arrangement['non_null_count'] = dat_arrangement.notna().sum(axis=1)
dat_arrangement.head()

      AR_ID  YEAR  DEBT_RATIO   DPD  M_LAST_DPD  non_null_count
0  76269627  2023    0.330044   NaN         NaN               3
1  53720950  2023    0.085891   NaN         NaN               3
2  46362866  2024    0.720821   8.0         8.0               5
3  60295607  2023    0.845081   NaN         NaN               3
4  63029620  2023    0.821967  43.0         0.0               5

In [17]:
dat_arrangement_clean = (
    dat_arrangement
        .sort_values('non_null_count', ascending=False)
        .drop_duplicates(subset=['YEAR', 'AR_ID'])
)
print(dat_arrangement_clean.shape)
print(dat_arrangement_clean[['YEAR', 'AR_ID']].drop_duplicates().shape)

(34262, 6)
(34262, 2)

In [18]:
scoring_with_arrangement = pd.merge(
    dat_scoring,
    dat_arrangement_clean,
    on=['YEAR', 'AR_ID'],
    how='left'
)
print(scoring_with_arrangement.shape)
print(scoring_with_arrangement.shape[0] == dat_scoring.shape[0])
scoring_with_arrangement.head()

(36000, 10)
True

,YEAR,IP_ID,AR_ID,PD,PD_POOL,DFLT_FLAG,DEBT_RATIO,DPD,M_LAST_DPD,non_null_count
0,2022,CFG053,2795120,9.925260e-01,5.0,1,1.000000,1.0,6.0,5.0
1,2022,NNA451,10210477,2.656939e-05,1.0,0,0.804767,NaN,NaN,3.0
2,2022,VLZ931,24787848,3.514735e-06,1.0,0,0.136493,NaN,NaN,3.0
3,2022,VVF064,35869938,5.868028e-06,1.0,0,0.522421,NaN,NaN,3.0
4,2022,DXH176,71765042,8.378070e-07,1.0,0,0.295783,NaN,NaN,3.0

In [72]:
scoring_with_arrangement.to_csv("../data_processed/scoring_with_arrangement.csv", index=False)